ToDoList/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoList.Models
{
    public class ToDo
    {
        public int Id { get; set; }
        public bool IsCompleted { get; set; }
        public string Description { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

ToDoList/Controllers/ToDoesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class ToDoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ToDoes
        public ActionResult Index()
        {
            //db.Database.ExecuteSqlCommand("TRUNCATE TABLE ToDoes");
            //db.SaveChanges();
            return View();
        }

        private IEnumerable<ToDo> GetMyToDoes()
        {
            string currentUserId = User.Identity.GetUserId();
            var currentUser = db.Users.FirstOrDefault
                (x => x.Id == currentUserId);

            return db.ToDos.ToList().Where(x => x.User == currentUser);
        }

        //Call partial view of table to have create in the same page
        public ActionResult BuildToDoTable()
        {
            return PartialView("_ToDoTable", GetMyToDoes());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "Id,Description")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(toDo.Description))
                {
                    if (!string.IsNullOrWhiteSpace(toDo.Description))
                    {
                        string currentUserId = User.Identity.GetUserId();
                        ApplicationUser currentUser = db.Users.FirstOrDefault
                            (x => x.Id == currentUserId);
                        toDo.User = currentUser;
                        toDo.IsCompleted = false;
                        db.ToDos.Add(toDo);
                        db.SaveChanges();
                    }
                }

            }

            return PartialView("_ToDoTable", GetMyToDoes());
        }

        // GET: ToDoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }

        // POST: ToDoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IsCompleted,Description")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toDo);
        }

        [HttpPost]
        public ActionResult AJAXEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.IsCompleted = value;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_ToDoTable", GetMyToDoes());
            }
        }

        // GET: ToDoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }

        // POST: ToDoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ToDo toDo = db.ToDos.Find(id);
            db.ToDos.Remove(toDo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AJAXDelete(ToDo todo)
        {
            if (todo == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                db.Database.ExecuteSqlCommand("TRUNCATE TABLE ToDoes");
                db.SaveChanges();
                return View("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToDoList/Views/ToDoes/Create.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IsCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCompleted)
                    @Html.ValidationMessageFor(model => model.IsCompleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDoes/Delete.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToDoList/Views/ToDoes/Details.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCompleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToDoList/Views/ToDoes/Edit.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.IsCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCompleted)
                    @Html.ValidationMessageFor(model => model.IsCompleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDoes/Index.cshtml
@model ToDoList.Models.ToDo

<div class="col-md-8 col-md-offset-2"
     style="margin-top:30px; border: 1px solid #ccc; padding-bottom:20px; padding-top:10px;  box-shadow:5px 5px 10px rgba(0,0,0,.6)">
    <div class="panel panel-default">
        <div class="panel-body">
            <h4 style="text-align: center;"> To Do List</h4>

            <div id="todoCreateForm" style="margin-top: 50px;">
                @using (Ajax.BeginForm("AJAXCreate", "ToDoes",
            new AjaxOptions
            {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "POST",
                UpdateTargetId = "tableDiv"
            }))
                {
                    <div class="form-group">
                        @Html.AntiForgeryToken()
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "New Task"} })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                        </div>
                        <button type="submit" id="addTask" class="btn btn-warning">Add Task</button>
                    </div>
                }
            </div>
            <div id="tableDiv"></div>

        </div>
    </div>
</div>


@section Scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        $(document).ready(function () {
            $.ajax({
                url: '/ToDoes/BuildToDoTable',
                success: function (result) {
                    $('#tableDiv').html(result);
                }
            });
        })

        function CloseFunction() {
            url: '/ToDoes/AJAXDelete',
            onsubmit();
            //var table = document.getElementById("tableDiv");
            //var rowCount = table.rows.length;
            //for (var i = rowcount - 1; i >= 0; i--) {
            //    table.remove(i);
            //}
        }
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDoes/_ToDoTable.cshtml
@model IEnumerable<ToDoList.Models.ToDo>

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.CheckBoxFor(modelItem => item.IsCompleted, new { id = item.Id, @class = "ActiveCheck" })
            </td>
            <td>
                @if (!item.IsCompleted)
                {
                    @Html.DisplayFor(modelItem => item.Description)
                }
                else
                {
                    <div class="CompletedToDo">@Html.DisplayFor(modelItem => item.Description)</div>
                }

            </td>
            <td>
                <button type="submit" class="btn btn-default">@Html.ActionLink("Remove", "Delete", new { id = item.Id })</button>
            </td>
        </tr>
    }

</table>

<script>
    $(document).ready(function () {
        $('.ActiveCheck').change(function () {
            var self = $(this);
            var id = self.attr('id');
            var value = self.prop('checked');

            $.ajax({
                url: '/ToDoes/AJAXEdit',
                data: {
                    id: id,
                    value: value
                },
                type: 'POST',
                success: function (result) {
                    $('#tableDiv').html(result);
                }
            });
        });
    });
</script>